stage:
  image_to_caption:
    is_component: False
    model: 'blip2'
    model_chkpt: "Salesforce/blip2-opt-2.7b"
  caption_to_keyword:
    is_component: False
    model: 'spacy'
    model_chkpt: "en_core_web_sm"
  text_to_embed:
    is_component: False
    model: 'glove'
  embed_to_cat:
    is_component: False
  image_text_to_box:
    is_component: True
    model: 'dino'
    model_chkpt: "/tmp/weights/groundingdino_swint_ogc.pth"
    model_config: "/tmp/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py"
    box_thresh: 0.35
    text_thresh: 0.25
    class_type: mod_class_from_embd

path:
  save_dir: '/me/building_pipeline'
  images: '/me/public_validation_set_release_2.1/images'
  glove_dir: '/tmp/GloVe'

file:
  metadata: '/me/examples/public_validation_set_2.1_glove_cats.json'
  metadata_save: '/public_validation_set_release_2.1_blip2.json'
  mod_cats: '/me/food_recognition_round2_categories_modified.txt'

var:
  device: 'cuda'
  testing: True