stage:
  image_to_caption:
    is_component: False
    model: 'blip2'
    model_chkpt: "Salesforce/blip2-opt-2.7b"
    temperature: 0.2
    top_p: 0.1
    num_beams: 1
  caption_to_keyword:
    is_component: False
    model: 'spacy'
    model_chkpt: "en_core_web_sm"
  text_to_embed:
    is_component: False
    model: 'glove'
  embed_to_cat:
    is_component: False
  image_text_to_box:
    is_component: False
    model: 'dino'
    model_chkpt: "/tmp/weights/groundingdino_swint_ogc.pth"
    model_config: "/tmp/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py"
    box_thresh: 0.35
    text_thresh: 0.25
    class_type: mod_class_from_embd
  image_box_to_mask:
    is_component: True
    model: 'sam'
    model_chkpt: "/tmp/MobileSAM/weights/mobile_sam.pt"
    model_encoder: "vit_t"


path:
  save_dir: '/me/building_pipeline'
  images: '/me/public_validation_set_release_2.1/images'
  glove_dir: '/tmp/GloVe'
  mask_dir: '/tmp/masks'

file:
  metadata: '/me/examples/public_validation_set_release_2.1_blip2_glove_dino.json'
  metadata_save: '/me/examples/public_validation_set_release_2.1_blip2_glove_dino_sam.json'
  mod_cats: '/me/food_recognition_round2_categories_modified.txt'

var:
  device: 'cuda'
  testing: False