stage:
  image_to_caption:
    is_component: False
    model: 'blip2'
    specific_model: "Salesforce/blip2-opt-2.7b"
  caption_to_keyword:
    is_component: False
    model: 'spacy'
    specific_model: "en_core_web_sm"
  text_to_embed:
    is_component: True
    model: 'glove'
  embed_to_cat:
    is_component: True

path:
  save_dir: '/me/building_pipeline'
  images: '/me/public_validation_set_release_2.1/images'
  glove_dir: '/tmp/GloVe'

file:
  metadata: '/me/examples/public_validation_set_2.1_blip2_spacy.json'
  metadata_save: '/public_validation_set_release_2.1_blip2.json'
  mod_cats: '/me/food_recognition_round2_categories_modified.txt'

var:
  device: 'cuda'
  testing: True