stage:
  image_to_caption:
    is_component: True
    model: 'blip2'
    model_variation: "Salesforce/blip2-opt-2.7b"
  caption_to_keyword:
    is_component: True
    model: 'glove'

path:
  save_dir: '/me/building_pipeline'
  images: '/me/public_validation_set_release_2.1/images'

file:
  metadata: '/me/public_validation_set_release_2.1/annotations.json'
  metadata_save: '/public_validation_set_release_2.1_blip2.json'

var:
  device: 'cuda'
  testing: True