version: "3.8"

services:
  meal-segmentation:
      image: meal-segmentation:latest
      container_name: meal-segmentation
      volumes:
        - ../:/me
      # restart: always 
      # command: bash -c '. ./bin/grounding_dino.sh; sleep infinity'
      command: bash -c 'sleep infinity'
      runtime: nvidia
      environment:
        HOME: /tmp
